### PR TITLE
more V2 work

### PR DESCRIPTION
**Pull request by MistApproach**

### CODE REVIEW

**Comment by MistApproach** [comment]
FarcasterAccount token revocation not implemented yet.
I feel like this needs better integration with time.

**Comment by TheLDB** [comment]
hey! love this PR just a couple things

working on token revocation right now (specific, and all tokens)

but should we rename auth_token() to something like gen_auth_token() or get? the naming just feels a little off

**Comment by TheLDB** [comment]
just pushed some ground structure for token revocation, despite the API not being there yet, just make our future lives easier

question about auth_token still stands, though

**Comment by MistApproach** [comment]
https://github.com/TheLDB/farcaster-rs/issues/13

**Comment by MistApproach** [comment]
> but should we rename auth_token() to something like gen_auth_token() or get? the naming just feels a little off

I think you're on to something. My thinking was `Farcaster::functions()` will call internally `self.account.auth_token()` to obtain Authentication Token when needed by _reqwest_. But `get_auth_token()` sounds equally good - do whatever feels more intuitive to you.
I would avoid `get()` as FarcasterAccount can possibly encapsulate more than just Authentication Token. That's why i tried to stick with `auth_token` for everything relating to Merkle V2 API token. Some of the non-public functions don't follow this convention as they basically act as a bridge to your auth code - and i thought of it as temporary btw.

As always i'm open for suggestions!
If we stick with above convention `revoke_session_token` should become `revoke_auth_token` propably?

**Comment by TheLDB** [comment]
cool, just made those changes.

thinking abt just leaving this branch & pr open so we can continue to work in here, then merge when we seem fit?

any thoughts

**Comment by MistApproach** [comment]
> thinking abt just leaving this branch & pr open so we can continue to work in here, then merge when we seem fit?

It's a bit easier to keep my fork in sync when you merge PR. Besides v2-api branch is a huge WIP so we're not breaking anything by merging. Just my two cents.

**Comment by MistApproach** [comment]
Looking at v2 docs they changed from using user address to fid in many places. Think we need FIR support in Registry ASAP. Will try to work on this.
As for the v2 functionality i think we're getting close. The only major thing left is to rewrite using v2 endpoints and auth headers. Apart from this some v2 structs might need adjusting.

**Comment by TheLDB** [comment]
kk, will merge & merge all future PR's ASAP

also i'll look into FIR support tonight

and will look into endpoints

**Pull request merged**
